version: "3.9"
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: moot-db 
    environment:
      POSTGRES_USER: 'erikrios'
      POSTGRES_PASSWORD: 'erikrios'
      POSTGRES_DB: 'moot_db'
    ports: 
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - moot-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  moot-db-volume:
