// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	payload "github.com/kelompok-22-capstone-project/forum-group-discussion-backend/model/payload"
	response "github.com/kelompok-22-capstone-project/forum-group-discussion-backend/model/response"
	mock "github.com/stretchr/testify/mock"
)

// ThreadService is an autogenerated mock type for the ThreadService type
type ThreadService struct {
	mock.Mock
}

// AddModerator provides a mock function with given fields: ctx, p, threadID, accessorUserID
func (_m *ThreadService) AddModerator(ctx context.Context, p payload.AddRemoveModerator, threadID string, accessorUserID string) error {
	ret := _m.Called(ctx, p, threadID, accessorUserID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, payload.AddRemoveModerator, string, string) error); ok {
		r0 = rf(ctx, p, threadID, accessorUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeFollowingState provides a mock function with given fields: ctx, threadID, accessorUserID
func (_m *ThreadService) ChangeFollowingState(ctx context.Context, threadID string, accessorUserID string) error {
	ret := _m.Called(ctx, threadID, accessorUserID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, threadID, accessorUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeLikeState provides a mock function with given fields: ctx, threadID, accessorUserID
func (_m *ThreadService) ChangeLikeState(ctx context.Context, threadID string, accessorUserID string) error {
	ret := _m.Called(ctx, threadID, accessorUserID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, threadID, accessorUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, accessorUserID, p
func (_m *ThreadService) Create(ctx context.Context, accessorUserID string, p payload.CreateThread) (string, error) {
	ret := _m.Called(ctx, accessorUserID, p)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, payload.CreateThread) string); ok {
		r0 = rf(ctx, accessorUserID, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, payload.CreateThread) error); ok {
		r1 = rf(ctx, accessorUserID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComment provides a mock function with given fields: ctx, threadID, accessorUserID, p
func (_m *ThreadService) CreateComment(ctx context.Context, threadID string, accessorUserID string, p payload.CreateComment) (string, error) {
	ret := _m.Called(ctx, threadID, accessorUserID, p)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, payload.CreateComment) string); ok {
		r0 = rf(ctx, threadID, accessorUserID, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, payload.CreateComment) error); ok {
		r1 = rf(ctx, threadID, accessorUserID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, accessorUserID, role, ID
func (_m *ThreadService) Delete(ctx context.Context, accessorUserID string, role string, ID string) error {
	ret := _m.Called(ctx, accessorUserID, role, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, accessorUserID, role, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, accessorUserID, page, limit, query
func (_m *ThreadService) GetAll(ctx context.Context, accessorUserID string, page uint, limit uint, query string) (response.Pagination[response.ManyThread], error) {
	ret := _m.Called(ctx, accessorUserID, page, limit, query)

	var r0 response.Pagination[response.ManyThread]
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, string) response.Pagination[response.ManyThread]); ok {
		r0 = rf(ctx, accessorUserID, page, limit, query)
	} else {
		r0 = ret.Get(0).(response.Pagination[response.ManyThread])
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, string) error); ok {
		r1 = rf(ctx, accessorUserID, page, limit, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, accessorUserID, ID
func (_m *ThreadService) GetByID(ctx context.Context, accessorUserID string, ID string) (response.Thread, error) {
	ret := _m.Called(ctx, accessorUserID, ID)

	var r0 response.Thread
	if rf, ok := ret.Get(0).(func(context.Context, string, string) response.Thread); ok {
		r0 = rf(ctx, accessorUserID, ID)
	} else {
		r0 = ret.Get(0).(response.Thread)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accessorUserID, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComments provides a mock function with given fields: ctx, threadID, page, limit
func (_m *ThreadService) GetComments(ctx context.Context, threadID string, page uint, limit uint) (response.Pagination[response.Comment], error) {
	ret := _m.Called(ctx, threadID, page, limit)

	var r0 response.Pagination[response.Comment]
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint) response.Pagination[response.Comment]); ok {
		r0 = rf(ctx, threadID, page, limit)
	} else {
		r0 = ret.Get(0).(response.Pagination[response.Comment])
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint) error); ok {
		r1 = rf(ctx, threadID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveModerator provides a mock function with given fields: ctx, p, threadID, accessorUserID
func (_m *ThreadService) RemoveModerator(ctx context.Context, p payload.AddRemoveModerator, threadID string, accessorUserID string) error {
	ret := _m.Called(ctx, p, threadID, accessorUserID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, payload.AddRemoveModerator, string, string) error); ok {
		r0 = rf(ctx, p, threadID, accessorUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, accessorUserID, ID, p
func (_m *ThreadService) Update(ctx context.Context, accessorUserID string, ID string, p payload.UpdateThread) error {
	ret := _m.Called(ctx, accessorUserID, ID, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, payload.UpdateThread) error); ok {
		r0 = rf(ctx, accessorUserID, ID, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewThreadService interface {
	mock.TestingT
	Cleanup(func())
}

// NewThreadService creates a new instance of ThreadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThreadService(t mockConstructorTestingTNewThreadService) *ThreadService {
	mock := &ThreadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
