// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	generator "github.com/kelompok-22-capstone-project/forum-group-discussion-backend/utils/generator"
	mock "github.com/stretchr/testify/mock"

	payload "github.com/kelompok-22-capstone-project/forum-group-discussion-backend/model/payload"

	response "github.com/kelompok-22-capstone-project/forum-group-discussion-backend/model/response"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tp, p
func (_m *CategoryService) Create(ctx context.Context, tp generator.TokenPayload, p payload.CreateCategory) (string, error) {
	ret := _m.Called(ctx, tp, p)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, generator.TokenPayload, payload.CreateCategory) string); ok {
		r0 = rf(ctx, tp, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, generator.TokenPayload, payload.CreateCategory) error); ok {
		r1 = rf(ctx, tp, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, tp, id
func (_m *CategoryService) Delete(ctx context.Context, tp generator.TokenPayload, id string) error {
	ret := _m.Called(ctx, tp, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, generator.TokenPayload, string) error); ok {
		r0 = rf(ctx, tp, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *CategoryService) GetAll(ctx context.Context) ([]response.Category, error) {
	ret := _m.Called(ctx)

	var r0 []response.Category
	if rf, ok := ret.Get(0).(func(context.Context) []response.Category); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByCategory provides a mock function with given fields: ctx, tp, categoryID, page, limit
func (_m *CategoryService) GetAllByCategory(ctx context.Context, tp generator.TokenPayload, categoryID string, page uint, limit uint) (response.Pagination[response.ManyThread], error) {
	ret := _m.Called(ctx, tp, categoryID, page, limit)

	var r0 response.Pagination[response.ManyThread]
	if rf, ok := ret.Get(0).(func(context.Context, generator.TokenPayload, string, uint, uint) response.Pagination[response.ManyThread]); ok {
		r0 = rf(ctx, tp, categoryID, page, limit)
	} else {
		r0 = ret.Get(0).(response.Pagination[response.ManyThread])
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, generator.TokenPayload, string, uint, uint) error); ok {
		r1 = rf(ctx, tp, categoryID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tp, id, p
func (_m *CategoryService) Update(ctx context.Context, tp generator.TokenPayload, id string, p payload.UpdateCategory) error {
	ret := _m.Called(ctx, tp, id, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, generator.TokenPayload, string, payload.UpdateCategory) error); ok {
		r0 = rf(ctx, tp, id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoryService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryService(t mockConstructorTestingTNewCategoryService) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
